{{-- resources/views/components/background-rain.blade.php --}}
<div id="rain-container" class="fixed inset-0 z-0 pointer-events-none overflow-hidden">
    <!-- Rain Layer 1 (Front) -->
    <div id="rain-layer-1" class="absolute inset-0"></div>
    
    <!-- Rain Layer 2 (Middle) -->
    <div id="rain-layer-2" class="absolute inset-0 opacity-70"></div>
    
    <!-- Rain Layer 3 (Back) -->
    <div id="rain-layer-3" class="absolute inset-0 opacity-50"></div>
    
    <!-- Hydro Particles -->
    <div id="hydro-particles" class="absolute inset-0"></div>
    
    <!-- Water Surface Ripples -->
    <div id="water-ripples" class="absolute bottom-0 left-0 right-0 h-32">
        <!-- Will be generated by JS -->
    </div>
    
    <!-- Hydro Light Glows -->
    <div class="absolute top-1/4 left-1/4 w-64 h-64 bg-cyan-500/10 rounded-full blur-3xl"></div>
    <div class="absolute bottom-1/4 right-1/4 w-96 h-96 bg-blue-500/10 rounded-full blur-3xl"></div>
</div>